### ISSUE TITLE
Add a new field to project 

### ISSUE THREAD

**Issue by celinehuang** [hack4impact-mcgill/mu-crm-tool#102]
- add a new boolean field to the Project table: `is_completed` 
- this field is nullable=False
-  make a new migration

**Comment by SymPiracha** [comment]
@CurtisMIT  @celinehuang 

Seem to be running into an issue when I try to make a migration. I can't seem to figure it out. Any tips?
Im doing: python3 manage.py db upgrade

<img width="850" alt="Screenshot_1" src="https://user-images.githubusercontent.com/49314682/109448462-0662b980-7a14-11eb-8833-07b049eaa869.png">

**Comment by CurtisMIT** [comment]
@SymPiracha Is it ok if you check the following items?
- properly located .env with the correct content
- containers running with no issue (able to go on pgAdmin and see the database)
- most updated repository
- all tests are passing without any of your changes
