### ISSUE TITLE
Get all projects

### ISSUE THREAD

**Issue by celinehuang** [hack4impact-mcgill/mu-crm-tool#18]
Get all projects with the GET endpoint

Documentation on [Flask Blueprints](https://flask.palletsprojects.com/en/1.1.x/blueprints/#blueprints)
An example of the REST endpoints - https://github.com/celinehuang/kom_get_your_bucha/blob/master/backend/app/items/views.py

**Comment by CurtisMIT** [comment]
Resolved by #98
